language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run test
  # just check example dont crash waiting for real tests
  - pipenv run python examples/simple.py
  - pipenv run python examples/complex.py

after_success:
  - pipenv run codecov
