language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

install:
   - pip install --upgrade pip
   - pip install poetry
   - poetry install -v

script:
  - poetry run task test
  # just check example dont crash waiting for real tests
  - python examples/simple.py
  - python examples/complex.py

after_success:
  - pipenv run codecov
